kind = "mobile"
previewPath = "/aqar-mobile/"
title = "Aqar Mobile"
version = "1.0.0"
id = "artifacts/aqar-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/aqar-mobile/" ]
localPort = 18183

[services.development]
run = "pnpm --filter @workspace/aqar-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/aqar-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/aqar-mobile", "run", "serve" ]

[services.env]
PORT = "18183"
BASE_PATH = "/aqar-mobile/"
