// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ads/AdCitySquare.tsx": () => import("../components/mockups/ads/AdCitySquare.tsx"),
  "./components/mockups/ads/AdCityVertical.tsx": () => import("../components/mockups/ads/AdCityVertical.tsx"),
  "./components/mockups/ads/AdDataSquare.tsx": () => import("../components/mockups/ads/AdDataSquare.tsx"),
  "./components/mockups/ads/AdDataVertical.tsx": () => import("../components/mockups/ads/AdDataVertical.tsx"),
  "./components/mockups/ads/AdFamilySquare.tsx": () => import("../components/mockups/ads/AdFamilySquare.tsx"),
  "./components/mockups/ads/AdFamilyVertical.tsx": () => import("../components/mockups/ads/AdFamilyVertical.tsx"),
  "./components/mockups/ads/VideoMarketerAd.tsx": () => import("../components/mockups/ads/VideoMarketerAd.tsx"),
  "./components/mockups/logos/ClassicColumns.tsx": () => import("../components/mockups/logos/ClassicColumns.tsx"),
  "./components/mockups/logos/GeometricCity.tsx": () => import("../components/mockups/logos/GeometricCity.tsx"),
  "./components/mockups/logos/RoyalArch.tsx": () => import("../components/mockups/logos/RoyalArch.tsx"),
  "./components/mockups/logos/SmartEye.tsx": () => import("../components/mockups/logos/SmartEye.tsx")
};
