// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logos/ClassicColumns.tsx": () => import("../components/mockups/logos/ClassicColumns.tsx"),
  "./components/mockups/logos/GeometricCity.tsx": () => import("../components/mockups/logos/GeometricCity.tsx"),
  "./components/mockups/logos/RoyalArch.tsx": () => import("../components/mockups/logos/RoyalArch.tsx"),
  "./components/mockups/logos/SmartEye.tsx": () => import("../components/mockups/logos/SmartEye.tsx")
};
